
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-perl
  tolerations:   #as pod is having these tolerations, kube-scheduler allows the pod to be placed into the node even though if it is tainted kubectl taint nodes <node_name> hardware=gpu:NoSchedule
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  # nodeSelector:   #if node also having the lable as hardware: gpu then kube-scheduler will assign this pod to that node
  #   hardware: gpu



