apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchingExpressions:
          - key: hardware   #with these labels alredy nodes are labelled, it it matches then pods will be scheduled in those nodes.
            operator: In
            values:
            - gpu
  containers:
  - name: nginx
    image: nginx:stable-perl
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"