apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100  #NodeAffinityWeight
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - amd
      - weight: 1  #instead of nodeSelectorTerms it will have weightage and preference and more wieghtage have more preference meaning(1-100) 50>10>1
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - gpu
  containers:
  - name: nginx
    image: nginx:stable-perl
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"